# Generated by Django 4.2 on 2025-09-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên kỹ năng', max_length=100, unique=True)),
                ('normalized_name', models.CharField(help_text='Tên chuẩn hóa', max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='Danh mục kỹ năng', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kỹ năng',
                'verbose_name_plural': 'Kỹ năng',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='custom_skills',
            field=models.TextField(blank=True, help_text='Kỹ năng tự do (cách nhau bởi dấu phẩy)'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Kỹ năng có sẵn', to='accounts.skill'),
        ),
    ]
