# Generated by Django 4.2 on 2025-09-27 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_userprofile_custom_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Tài khoản đã xác thực'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Nhà tuyển dụng'), ('worker', 'Người tìm việc'), ('admin', 'Quản trị viên')], default='worker', max_length=10),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề khiếu nại', max_length=200)),
                ('description', models.TextField(help_text='Mô tả chi tiết')),
                ('complaint_type', models.CharField(choices=[('job_posting', 'Bài đăng việc làm'), ('user_behavior', 'Hành vi người dùng'), ('payment', 'Thanh toán'), ('technical', 'Kỹ thuật'), ('other', 'Khác')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang xử lý'), ('resolved', 'Đã giải quyết'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khiếu nại',
                'verbose_name_plural': 'Khiếu nại',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('user_verified', 'Xác thực người dùng'), ('user_banned', 'Cấm người dùng'), ('complaint_resolved', 'Giải quyết khiếu nại'), ('skill_added', 'Thêm kỹ năng'), ('skill_updated', 'Cập nhật kỹ năng'), ('system_config', 'Cấu hình hệ thống'), ('data_export', 'Xuất dữ liệu')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_activities', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoạt động Admin',
                'verbose_name_plural': 'Hoạt động Admin',
                'ordering': ['-created_at'],
            },
        ),
    ]
