# Generated by Django 5.2.6 on 2025-09-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_alter_user_user_type_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Mỗi số điện thoại chỉ được đăng ký 1 tài khoản', max_length=15, null=True, unique=True),
        ),
    ]
