# Generated by Django 5.2.6 on 2025-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_map_url',
            field=models.URLField(blank=True, help_text='Link Google Maps đến địa chỉ của bạn (tùy chọn)', null=True),
        ),
    ]
