# Generated by Django 5.2.6 on 2025-12-03 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_skill_category_to_foreignkey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề thông báo', max_length=200)),
                ('message', models.TextField(help_text='Nội dung thông báo')),
                ('notification_type', models.CharField(choices=[('application_accepted', 'Đơn ứng tuyển được chấp nhận'), ('application_rejected', 'Đơn ứng tuyển bị từ chối'), ('new_application', 'Có đơn ứng tuyển mới'), ('job_full', 'Công việc đã đủ người'), ('system', 'Thông báo hệ thống')], default='system', max_length=30)),
                ('is_read', models.BooleanField(default=False, help_text='Đã đọc')),
                ('link', models.CharField(blank=True, help_text='Link liên quan (URL)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
