# Generated by Django 4.2 on 2025-09-23 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên danh mục công việc', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Mô tả danh mục')),
                ('icon', models.CharField(blank=True, help_text='CSS class cho icon', max_length=50)),
                ('color', models.CharField(default='#007bff', help_text='Màu sắc hiển thị (hex)', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Danh mục công việc',
                'verbose_name_plural': 'Danh mục công việc',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề bài đăng', max_length=200)),
                ('description', models.TextField(help_text='Mô tả chi tiết công việc')),
                ('location', models.CharField(help_text='Địa điểm làm việc', max_length=200)),
                ('work_date', models.DateField(help_text='Ngày làm việc')),
                ('work_time_start', models.TimeField(help_text='Giờ bắt đầu')),
                ('work_time_end', models.TimeField(help_text='Giờ kết thúc')),
                ('duration_hours', models.DecimalField(decimal_places=2, help_text='Số giờ làm việc', max_digits=5)),
                ('payment_type', models.CharField(choices=[('hourly', 'Theo giờ'), ('daily', 'Theo ngày'), ('fixed', 'Cố định')], default='hourly', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Số tiền (VND)', max_digits=10)),
                ('required_skills', models.TextField(blank=True, help_text='Kỹ năng yêu cầu (cách nhau bởi dấu phẩy)')),
                ('experience_required', models.PositiveIntegerField(default=0, help_text='Số năm kinh nghiệm yêu cầu')),
                ('number_of_workers', models.PositiveIntegerField(default=1, help_text='Số lượng người cần tuyển')),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã đăng'), ('closed', 'Đã đóng'), ('expired', 'Hết hạn')], default='draft', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Thấp'), ('normal', 'Bình thường'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='normal', max_length=10)),
                ('application_deadline', models.DateTimeField(help_text='Hạn nộp đơn ứng tuyển')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.jobcategory')),
                ('employer', models.ForeignKey(limit_choices_to={'user_type': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài đăng việc làm',
                'verbose_name_plural': 'Bài đăng việc làm',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('accepted', 'Được chấp nhận'), ('rejected', 'Bị từ chối'), ('withdrawn', 'Đã rút lại')], default='pending', max_length=10)),
                ('cover_letter', models.TextField(blank=True, help_text='Thư xin việc')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Mức lương đề xuất (VND)', max_digits=10, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(limit_choices_to={'user_type': 'worker'}, on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobpost')),
            ],
            options={
                'verbose_name': 'Đơn ứng tuyển',
                'verbose_name_plural': 'Đơn ứng tuyển',
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
