# Generated by Django 5.2.6 on 2025-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Mức lương đề xuất (Không sử dụng - Lấy theo mức lương công việc)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='application_deadline',
            field=models.DateTimeField(blank=True, editable=False, help_text='Không sử dụng - Sẽ tự động lấy theo thời gian bắt đầu', null=True),
        ),
    ]
