# Generated by Django 5.2.6 on 2025-10-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='payment_type',
            field=models.CharField(choices=[('hourly', 'Theo giờ'), ('shift', 'Theo ca (lương cố định cả ngày)')], default='hourly', max_length=10),
        ),
    ]
