# Generated by Django 5.2.6 on 2025-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_update_payment_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='priority',
            field=models.CharField(choices=[('normal', 'Bình thường'), ('high', 'Cao')], default='normal', max_length=10),
        ),
    ]
