# Generated by Django 5.2.6 on 2025-10-08 09:46

from django.db import migrations


def update_priority_data(apps, schema_editor):
    """Cập nhật dữ liệu priority để chỉ giữ lại 'normal' và 'high'"""
    JobPost = apps.get_model('jobs', 'JobPost')
    
    # Cập nhật 'low' thành 'normal'
    JobPost.objects.filter(priority='low').update(priority='normal')
    
    # Cập nhật 'urgent' thành 'high'  
    JobPost.objects.filter(priority='urgent').update(priority='high')
    
    print("Updated priority data: 'low' -> 'normal', 'urgent' -> 'high'")


def reverse_priority_data(apps, schema_editor):
    """Reverse operation - không thể khôi phục chính xác được"""
    # Không thể khôi phục chính xác vì đã mất thông tin gốc
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_update_priority_choices'),
    ]

    operations = [
        migrations.RunPython(update_priority_data, reverse_priority_data),
    ]
