# Generated by Django 5.2.6 on 2025-10-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_update_priority_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='location_map_url',
            field=models.URLField(blank=True, help_text='Link Google Maps đến địa điểm làm việc', null=True),
        ),
    ]
