# Generated by Django 5.2.6 on 2025-12-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_add_location_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Vĩ độ GPS', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Kinh độ GPS', max_digits=9, null=True),
        ),
    ]
